name: CI / CD

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1

      - name: Install Dependencies
        run: npm ci
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          tags: ghcr.io/it-for-us/devops-tasks:latest

      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          kubeconfig: ${{secrets.KUBERNETES_SECRET}}

      - name: Deploy to the Kubernetes cluster
        uses: Azure/k8s-deploy@v4
        with:
          namespace: devops
          manifests: kubernetes.yml
          images: firatkucuk/devops-tasks:latest
